import assert from 'node:assert/strict';
import {mkdtemp,readFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {CDP} from '../viewport.mjs';
const exec=promisify(execFile),helper=new URL('../viewport.mjs',import.meta.url).pathname,sleep=ms=>new Promise(r=>setTimeout(r,ms));
const server=createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.setHeader('Permissions-Policy','display-capture=()');res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Capture denied fixture</title><style>body{margin:0;background:#123;color:#eef}button{position:absolute;left:30px;top:30px;width:100px;height:50px}</style><button id="counter" onclick="this.textContent=Number(this.textContent)+1">0</button>');});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const state=await mkdtemp('/tmp/screenhop-framed-test-');const run=async(...args)=>JSON.parse((await exec(process.execPath,[helper,'--state',state,...args],{timeout:40000})).stdout);let source,viewer;
try{const launched=await run('--headless','--device','iphone-13','--url',`http://127.0.0.1:${server.address().port}`);const connect=async folder=>{const[port,path]=(await readFile(`${state}/${folder}/DevToolsActivePort`,'utf8')).trim().split('\n');return CDP.connect(`ws://127.0.0.1:${port}${path}`)};source=await connect('browser');viewer=await connect('viewer-browser');const{sessionId:page}=await source.send('Target.attachToTarget',{targetId:launched.targetId,flatten:true});const{sessionId:view}=await viewer.send('Target.attachToTarget',{targetId:launched.viewerTargetId,flatten:true});const evaluate=async expression=>(await viewer.send('Runtime.evaluate',{expression,returnByValue:true},view)).result.value;let result;for(let i=0;i<130;i++){result=await evaluate(`({mode:typeof rtcMode==='undefined'?'unknown':rtcMode,jpeg:document.querySelector('#display')?.naturalWidth,video:document.querySelector('#rtc-video')?.videoWidth})`);if(result.mode==='jpeg'&&result.jpeg>0)break;await sleep(100)}assert.equal(result.mode,'jpeg');assert.ok(result.jpeg>0,JSON.stringify(result));assert.equal(result.video,0);await evaluate(`input({kind:'mouse',type:'mousePressed',x:60,y:50,button:'left',buttons:1,clickCount:1,modifiers:0});input({kind:'mouse',type:'mouseReleased',x:60,y:50,button:'left',buttons:0,clickCount:1,modifiers:0});`);await sleep(200);assert.equal((await source.send('Runtime.evaluate',{expression:'counter.textContent',returnByValue:true},page)).result.value,'1');console.log('PASS denied display-capture policy: automatic JPEG fallback and interactive input. '+JSON.stringify(result));}finally{source?.ws.close();viewer?.ws.close();await run('--close').catch(()=>{});server.closeAllConnections();server.close();}
